# File: gradle/libs.versions.toml

[versions]
agp = "8.9.2"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycle = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.04.01"
composeCompiler = "1.5.14" # Keep this, used by composeOptions
msal = "6.0.0"
materialIcons = "1.7.8"
# --- Hilt Version ---
hilt = "2.51.1"
# --- Coroutines Version ---
coroutines = "1.8.1" # Or your preferred stable version (e.g., 1.7.3) - ADDED
# --- Org JSON (if needed by GraphApiHelper) ---
orgJson = "20240303" # Or a recent stable version - ADDED

# Optional: AndroidX Hilt extension versions (if used later)
# hiltExt = "1.2.0"
# hiltNavCompose = "1.2.0"

[libraries]
# --- Kotlin ---
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" } # *** ADDED ***
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" } # *** ADDED ***

# --- AndroidX Core & Lifecycle ---
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# --- Compose ---
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIcons" }

# --- Microsoft Authentication ---
microsoft-msal = { group = "com.microsoft.identity.client", name = "msal", version.ref = "msal" }

# --- Hilt ---
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
# Optional: AndroidX Hilt extensions (if used later)
# androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
# androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavCompose" }

# --- JSON Parsing ---
org-json = { group = "org.json", name = "json", version.ref = "orgJson" } # *** ADDED ***

# --- Testing ---
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

javax-inject = { group = "javax.inject", name = "javax.inject", version = "1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
# --- Hilt ---
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
# --- Kotlin Kapt ---
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
